# Generated by Django 4.2.7 on 2023-12-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('country', models.CharField(max_length=221)),
                ('image', models.ImageField(upload_to='home/')),
                ('code', models.IntegerField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('data_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=221)),
                ('project', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=221)),
                ('message', models.CharField(max_length=221)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=221)),
                ('title', models.CharField(max_length=221)),
                ('place', models.CharField(max_length=221)),
                ('content', models.CharField(max_length=221)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
