# Generated by Django 4.2.7 on 2023-12-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_servismodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skil_name', models.CharField(max_length=221)),
                ('percent', models.IntegerField()),
            ],
        ),
    ]
