# Generated by Django 4.2.7 on 2023-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_myskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='projects/')),
                ('title', models.CharField(max_length=221)),
                ('direction', models.CharField(max_length=221)),
            ],
        ),
    ]
