# Generated by Django 4.2.7 on 2023-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0007_remove_ourblog_user_ourblog_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='website',
            field=models.CharField(default=1, max_length=221),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
