# Generated by Django 4.2.7 on 2023-12-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0008_contactmodel_website_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(default=1, max_length=221),
            preserve_default=False,
        ),
    ]
