# Generated by Django 4.2.7 on 2023-12-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0010_contactmodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='telegram',
            field=models.CharField(default=1, max_length=221),
            preserve_default=False,
        ),
    ]
