# Generated by Django 4.2.7 on 2023-12-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0011_remove_contactmodel_email_contactmodel_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('subject', models.CharField(max_length=221)),
                ('message', models.CharField(max_length=221)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
