# Generated by Django 4.2.7 on 2023-12-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0012_contactmodelmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourblog',
            name='awards',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourblog',
            name='complateprojects',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourblog',
            name='cups_of_coffe',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourblog',
            name='happy_customers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
